name: CI/CD

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - name: Build
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/
  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build/
      - name: Sign & Publish
        run: |
          echo ${{ secrets.SIGNING_SECRET_KEYRING_FILE_B64 }} | base64 --decode > $SIGNING_SECRET_KEYRING_FILE
          ./gradlew publish \
                  -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
                  -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
                  -Psigning.secretKeyRingFile=$SIGNING_SECRET_KEYRING_FILE
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SIGNING_SECRET_KEYRING_FILE: /tmp/secring.gpg
